### ISSUE TITLE
Rename repo to “TreeGrid”

### ISSUE THREAD

**Issue by jouni** [vaadin/tree-grid#11]
The current repo name suggests that it would be a part of our web components collection, together with `vaadin-grid`, `vaadin-combo-box`, `vaadin-date-picker` and so on, which probably confuses some users.

I suggest we rename it to reflect the Java class explicitly.

**Comment by wbadam** [comment]
That sounds fair enough.

What do you think about it @samie? Looking at the repos, there are none with camel case name. Should we start that convention or just name it to `tree-grid` or `treegrid` or similar? Or a name that expresses that it's an add-on?

**Comment by samie** [comment]
Looks like the lowercasing is more like GitHub convention. But leaving out the "vaadin-" prefix should be clearer.

**Comment by wbadam** [comment]
Changed name to `tree-grid` and updated references in directory and in README.
