### ISSUE TITLE
will not compile under Vaadin 7.7.7

### ISSUE THREAD

**Issue by Snap252** [vaadin/tree-grid#16]
since Vaadin 7.7.7

	com.vaadin.client.widgets.Grid.getEscalator()
is public

so GWT will not compile anymore because

	org.vaadin.treegrid.client.TreeGrid.getEscalator()

is protected

	[INFO] Compiling module AppWidgetset
	[INFO]    Tracing compile failure path for type 'org.vaadin.treegrid.client.TreeGrid'
	[INFO]       [ERROR] Errors in 'jar:file:/C:/Users/MyUser/.m2/repository/com/vaadin/vaadin-treegrid/0.7.3/vaadin-treegrid-0.7.3.jar!/org/vaadin/treegrid/client/TreeGrid.java'
	[INFO]          [ERROR] Line 23: Cannot reduce the visibility of the inherited method from Grid<JsonObject>
	[INFO]    [ERROR] Aborting compile due to errors in some input files

for backward compatibility yours should be made public too

**Comment by wbadam** [comment]
Thanks, updated the modifier to make it compatible with both 7.7.6 and 7.7.7 versions.
