### ISSUE TITLE
Version 8 Compatibility

### ISSUE THREAD

**Issue by stevejenks** [vaadin/tree-grid#19]
Can we have a version of this that is compatible with Vaadin 8 please?

**Comment by wbadam** [comment]
Hi,

TreeGrid is going to be part of the framework starting version 8.1, expected to be released this spring. Please keep a watch out for it!

Best regards,
Adam

**Comment by stevejenks** [comment]
Hi, thanks for your response.  I'm very new to Vaadin and so this may not
have been the correct place to post the request (i.e. it's not a bug but
more of a request for information).  Would you be able to advise where
perhaps I can post such a request in the future and also if perhaps there
is a road-map showing future planned Vaaden releases and the expected
content of these releases?

Also, if I may, I have another question that you may be able to assist me
with.  I've been able to get a basic web-application up and running and was
looking at how I style some aspects of it.  I have a grid and was looking
to style the rows as a function of the values they contain.  I can see your
documentation (
https://vaadin.com/docs/-/part/framework/components/components-grid.html)
and specifically the mention of using something like this to makr the rows
to style...

grid.setStyleGenerator(person -> {
    // Style based on alive status
    person.isAlive() ? null : "dead";
});

...and then using CSS styling like...

.v-grid-row.dead {
    color: gray;
}

...to style the row as gray, however the one thing I have not yet been
able to work out or provide documentation for is how I apply this
styling to the grid component itself.  I'm sure your documentation
will cover this somewhere but looking through pages such a s this
(https://vaadin.com/docs/-/part/framework/layout/layout-csslayout.html)
I've not yet been able to find the correct means to apply this.

Regards,

Steve.

**Comment by Snap252** [comment]
your can set a special style class to the (tree-)grid instance with 
Component.addStyle("my-css-class");

then adapt the Scss like you did with your .v-grid-row.dead
for
.my-css-class { background-color: red;}

or anything else you can do with (S)CSS

The css-Layout is just a layout-manager, that tells the component how to place/layout its sub-components - that is no css-layout styling for the grid.
But this questions seems not to be specialized to the tree-grid but seems to be a common vaadin question. If my answer did not help yet - can you specialize your question a little bit, so I can give you more specific information.

Kind regards
