### ISSUE TITLE
Treegrid doesn't work correctly with addItemClickListener

### ISSUE THREAD

**Issue by rabat22** [vaadin/tree-grid#23]
I use Treegrid and I want use the method addItemClickListener but it doesn't work correctly.

For example, when I click on a line, I have the code on the method addItemClickListener who is executed but when I click on the text on a line, there is no code who is executed.

I don't have this problem with the grid but with the treegrid I have the problem.

First picture, I click on the line not on the text, it works

![image](https://cloud.githubusercontent.com/assets/25502578/24398513/050e535c-13aa-11e7-9aba-3c7a22e57145.png)

Second picture, I click on the line but on the text, it doesn't work

![image](https://cloud.githubusercontent.com/assets/25502578/24398540/1d17c730-13aa-11e7-86bb-149f80913642.png)

I send you the project test

[GridTest.zip](https://github.com/vaadin/tree-grid/files/875156/GridTest.zip)

**Comment by wbadam** [comment]
Hi,

Sorry for the late reply.

Please try with version 0.7.5 and fw version 7.7.9, and the problem should be solved.

Let me know and reopen if still persists.

Cheers,
Adam

**Comment by rabat22** [comment]
Thank you it works
