### ISSUE TITLE
Method when user click on node in a treegrid

### ISSUE THREAD

**Issue by rabat22** [vaadin/tree-grid#25]
Hi,

I want to know if it is possible to have a method to know when user click on node in a treegrid. There is the method addItemClickListener to know when user click on item in a line of the treegrid but there is no way to know when user click on node.

Could you help me please.

**Comment by wbadam** [comment]
Added events and listeners.

Listeners can be attached as follows:
```java
grid.addExpandListener(new ExpandEvent.ExpandListener() {
    @Override
    public void itemExpand(ExpandEvent event) {
        Notification.show("expanded");
    }
});

grid.addCollapseListener(new CollapseEvent.CollapseListener() {
    @Override
    public void itemCollapse(CollapseEvent event) {
        Notification.show("collapsed");
    }
});
```
