### ISSUE TITLE
Exception when reordering columns

### ISSUE THREAD

**Issue by wbadam** [vaadin/tree-grid#6]
`GridState#columnOrder` is not accessible via `getDeclaredField()` because it is in super class.
```
java.lang.NoSuchFieldException: columnOrder
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at com.vaadin.ui.Grid$3.columnsReordered(Grid.java:4716)
```

**Comment by enkaradura** [comment]
I am also getting an error when reordering columns, although the columns get ordered.
Anybody has a temporary solution for this?

**Comment by wbadam** [comment]
As temporary fix, replaced `GridServerRpc` with one that uses `getField()` instead of `getDeclaredField()` so that fields in state subclass could be accessed through reflection.

Should be removed when vaadin/framework#8342 gets approved.
