### ISSUE TITLE
srcoll row  get blank when grid height is not a fix height.

### ISSUE THREAD

**Issue by yogaY** [vaadin/tree-grid#9]
i hava a grid that contains 50 row, when the grid height is set to a fix pixels, evernthing goes well.
`final VerticalLayout layout = new VerticalLayout();`
` layout.setSpacing(true);`
` layout.setMargin(true);`
`layout.setSizeFull();`
`  final TreeGrid grid = new TreeGrid();`
`grid.setWidth("100%");`
`grid.setHeight(600, Unit.PIXELS);`
the result:
![well](https://cloud.githubusercontent.com/assets/1960427/21705673/594481b4-d3fc-11e6-8604-ae29dfa9d996.png)

then i set the grid  height to 70%;
`final VerticalLayout layout = new VerticalLayout();`
` layout.setSpacing(true);`
` layout.setMargin(true);`
`layout.setSizeFull();`
`  final TreeGrid grid = new TreeGrid();`
`grid.setWidth("100%");`
`grid.setHeight("70%");`
the srcoll bottom row is blank like
![good](https://cloud.githubusercontent.com/assets/1960427/21705736/a752d9f0-d3fc-11e6-9f01-b44d158cc51a.png)

click the blank row ,then the row go normal.

**Comment by Snap252** [comment]
I had the same problem.
It seems to be the first row that is not visible in the beginning

**Comment by wbadam** [comment]
Is this browser dependent? I couldn't reproduce on Chrome so far. What browser were you using?

Also, is the problem exclusive to TreeGrid or happens when using Grid as well?

**Comment by Snap252** [comment]
it happens in Firefox (51.0.1 (32-Bit))
and Chrome ( 56.0.2924.87 (64-bit) )

it seems to depend on the size of the component (just some pixels [rounding problem?])

No, it does not happen with normal vaadin grid.

**Comment by Snap252** [comment]
test class:

	package com.snap252.vaadin.pivot;
	
	import javax.servlet.annotation.WebServlet;
	
	import org.vaadin.treegrid.TreeGrid;
	
	import com.vaadin.annotations.Theme;
	import com.vaadin.annotations.VaadinServletConfiguration;
	import com.vaadin.data.Container.Hierarchical;
	import com.vaadin.data.Container.Indexed;
	import com.vaadin.server.VaadinRequest;
	import com.vaadin.server.VaadinServlet;
	import com.vaadin.ui.TreeTable;
	import com.vaadin.ui.UI;
	
	@Theme("demo")
	public class ErrorUI extends UI {
		@WebServlet(value = "/*")
		@VaadinServletConfiguration(productionMode = false, ui = ErrorUI.class)
		public static class Servlet extends VaadinServlet {
		}
	
		private static Indexed createDemoContainer() {
			/* just for getting a quick hierarchical */
			final TreeTable t = new TreeTable();
			{
				t.addContainerProperty("parentId", String.class, "");
				t.addContainerProperty("value", String.class, "");
				t.setHierarchyColumn("parentId");
	
				final int nrOfParents = 1;
				for (int i = 0; i < nrOfParents; i++)
					t.addItem(new Object[] { null, "this_is_parent" + i }, "root_id_" + i);
	
				for (int i = 0; i < 1000; i++) {
					final String parentId = "root_id_" + (i % nrOfParents);
					final String childId = "child_id_" + i;
					t.addItem(new Object[] { parentId, "child_" + i }, childId);
					t.setParent(childId, parentId);
				}
	
				final Hierarchical containerDataSource = t.getContainerDataSource();
				assert containerDataSource.rootItemIds().size() == nrOfParents : containerDataSource.rootItemIds() + "=>"
						+ nrOfParents;
			}
			return (Indexed) t.getContainerDataSource();
		}
	
		@Override
		protected void init(final VaadinRequest request) {
	
			final TreeGrid tg = new TreeGrid();
			tg.setContainerDataSource(createDemoContainer());
			tg.setHeight("350px");
			setContent(tg);
		}
	}
styles.scss:

	@import "../valo/valo.scss";
	@import "addons.scss";
	
	.demo {
		@include valo;
		@include addons;
	}

addons.scss: (just yours included)

	/* This file is automatically managed and will be overwritten from time to time. */
	/* Do not manually edit this file. */
	
	/* Provided by vaadin-treegrid-0.7.3.jar */
	@import "../../../VAADIN/addons/treegrid/treegrid.scss";
	
	
	/* Import and include this mixin into your project theme to include the addon themes */
	@mixin addons {
		@include treegrid;
	}
	

happens when expanding the root

**Comment by wbadam** [comment]
Thanks for the example, I managed to reproduce on both Chrome and Firefox on Windows. The issue apparently has to do with the scroll bars as it doesn't happen on MacOS (no fixed scroll bars there).

I could also reproduce on pure Grid when adding items with a button click.

It is probably the same issue as https://github.com/vaadin/framework/issues/7422

**Comment by Snap252** [comment]
Yes - seems to be the origin problem - then this issue should be closed - I think.
Thx for reporting it to the Vaadin guys.

**Comment by wbadam** [comment]
Fair enough, it gets a new label then and eyes on vaadin/framework#7422
